### ISSUE TITLE
Rewrite models to use Flask-SQLAlchemy

### ISSUE THREAD

**Issue by ecoerod** [rgoliveira/petreon#7]
Currently the models all use vanilla SQLAlchemy model, which is fine. However, it's unwieldy to use in Flask in big applications, which is why I suggest to move them into the Flask-SQLAlchemy extension, that we have already installed. There are a few steps in this process, which I'll lay down here, followed by the documentation required:

- [ ] Use the Flask-SQLAlchemy db settings and ORM, instead of vanilla 
  - [x] Translate all the model files into the new ORM's format. ([Flask-SQLAlchemy model](http://flask-sqlalchemy.pocoo.org/2.1/models/#simple-example))
  - [x] Rewrite the routes to work with this new format. ([Flask-SQLAlchemy CRUD](http://flask-sqlalchemy.pocoo.org/2.1/queries/#select-insert-delete))
  - [ ] Make an app factory with parametric DB instance and config. ([Flask App Factories](http://flask.pocoo.org/docs/0.12/patterns/appfactories/#factories-extensions))
  - [x] Redo the migrations using Flask-Migrate, wrapper for Alembic ([Flask-Migrate docs](https://flask-migrate.readthedocs.io/en/latest/))

This process should be done before #5 and #6, if we decide to jump to it. It'll make those other issues easier to complete.

**Comment by ecoerod** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Rewrite models to use Flask-SQLAlchemy](https://trello.com/c/IH3Fr8f3/18-rewrite-models-to-use-flask-sqlalchemy)

**Comment by ecoerod** [comment]
As an example of the model rewrite.
Before:
```python
from sqlalchemy import *
from sqlalchemy.orm import relationship
from models import Base
from models.custom_types import GUID
import uuid

class Donation(Base):
    __tablename__ = 'donation'

    uuid            = Column(GUID, primary_key=True, default=uuid.uuid4)
    campaign_uuid   = Column(GUID, ForeignKey('campaign.uuid'), nullable=False)
    donor_uuid      = Column(GUID, ForeignKey('donor.uuid'), nullable=False)
    date            = Column(Date, nullable=False)
    amount          = Column(Float(2))
```
After:
```python
from models import db
from models.custom_types import GUID #Maybe needs to change?
import uuid

class Donation(db.Model):

    uuid            = db.Column(GUID, primary_key=True, default=uuid.uuid4)
    campaign_uuid   = db.Column(GUID, db.ForeignKey('campaign.uuid'), nullable=False)
    donor_uuid      = db.Column(GUID, db.ForeignKey('donor.uuid'), nullable=False)
    date            = db.Column(db.Date, nullable=False)
    amount          = db.Column(db.Float(2))
```

**Comment by rgoliveira** [comment]
Thanks for including all the details. This should be marked as blocking.

**Comment by rgoliveira** [comment]
I'm on it. Should be done by tomorrow night.

**Comment by rgoliveira** [comment]
Ok, here's what I just pushed:

- [ ] Use the Flask-SQLAlchemy db settings and ORM, instead of vanilla 
  - [x] Translate all the model files into the new ORM's format. ([Flask-SQLAlchemy model](http://flask-sqlalchemy.pocoo.org/2.1/models/#simple-example)):
    - See d4bbef81d88647604d55c7991594fec7f0607b9e
  - [x] Rewrite the routes to work with this new format. ([Flask-SQLAlchemy CRUD](http://flask-sqlalchemy.pocoo.org/2.1/queries/#select-insert-delete))
    - See d4bbef81d88647604d55c7991594fec7f0607b9e (same as above)
  - [ ] Make an app factory with parametric DB instance and config. ([Flask App Factories](http://flask.pocoo.org/docs/0.12/patterns/appfactories/#factories-extensions))
  - [x] Redo the migrations using Flask-Migrate, wrapper for Alembic ([Flask-Migrate docs](https://flask-migrate.readthedocs.io/en/latest/)):
    - See 201228adec153c20ee5d9214415f341129d4406e
